### PR TITLE
merge docker script and containerd script into one

### PR DESCRIPTION
**Pull request by whitebear009**
For issue：[https://github.com/yuyicai/update-kube-cert/issues/13](https://github.com/yuyicai/update-kube-cert/issues/13)

### CODE REVIEW

**Comment by whitebear009** [comment]
@yuyicai Please check, thanks

**Review by yuyicai — APPROVED** [review]
LGTM

**Comment by yuyicai** [comment]
thanks!!! 👍

**Comment by yuyicai** [comment]
close #13

**Pull request merged**
